name: main

on:
  push:
    branches:
      - main

jobs:
  build_package_publish:
    name: "black → test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: black
        run: |
          make black
          
      - name: test
        run: |
          make test
